import postgres from "postgres"

import type {
  ChangeEvent,
  ChangeRecord,
  ChangeStatus,
  NewNote,
  NewTicket,
  TicketNote,
  TicketPatch,
  TicketRecord,
  TicketStatus,
  TicketStore,
} from "./types.ts"

export const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  title TEXT NOT NULL,
  severity TEXT NOT NULL,
  category TEXT NOT NULL,
  status TEXT NOT NULL,
  source TEXT NOT NULL,
  requester_name TEXT NOT NULL,
  requester_email TEXT NOT NULL DEFAULT '',
  assignee_email TEXT,
  site_name TEXT,
  site_id TEXT,
  asset_tag TEXT,
  asset_id TEXT,
  device_id TEXT,
  device_name TEXT,
  lockhaven_alert_id TEXT,
  lockhaven_session_id TEXT,
  lockhaven_access_request_id TEXT,
  recording_url TEXT,
  session_reason TEXT,
  notes TEXT NOT NULL DEFAULT '',
  time_spent_minutes INTEGER NOT NULL DEFAULT 0,
  resolution TEXT,
  created_by_sub TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS tickets_alert_id_uidx
  ON tickets (lockhaven_alert_id)
  WHERE lockhaven_alert_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS tickets_session_id_uidx
  ON tickets (lockhaven_session_id)
  WHERE lockhaven_session_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS tickets_access_request_id_uidx
  ON tickets (lockhaven_access_request_id)
  WHERE lockhaven_access_request_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS ticket_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  author_email TEXT NOT NULL DEFAULT '',
  author_name TEXT NOT NULL,
  body TEXT NOT NULL,
  minutes INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS changes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  title TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  requested_by_email TEXT NOT NULL,
  requested_by_name TEXT NOT NULL,
  approved_by_email TEXT,
  approved_at TIMESTAMPTZ,
  lockhaven_access_request_id TEXT,
  rollback_plan TEXT NOT NULL DEFAULT '',
  applied_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS change_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  change_id UUID NOT NULL REFERENCES changes(id) ON DELETE CASCADE,
  actor_email TEXT NOT NULL,
  actor_name TEXT NOT NULL,
  action TEXT NOT NULL,
  detail JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ingest_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source TEXT NOT NULL,
  event TEXT NOT NULL,
  ticket_id UUID REFERENCES tickets(id) ON DELETE SET NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
`

type Sql = ReturnType<typeof postgres>

export function createSql(databaseUrl: string) {
  return postgres(databaseUrl, { max: 10, idle_timeout: 20 })
}

export async function migrate(sql: Sql) {
  await sql.unsafe(SCHEMA_SQL)
}

function mapTicket(row: Record<string, unknown>): TicketRecord {
  return {
    id: String(row.id),
    number: Number(row.number),
    title: String(row.title),
    severity: row.severity as TicketRecord["severity"],
    category: row.category as TicketRecord["category"],
    status: row.status as TicketRecord["status"],
    source: row.source as TicketRecord["source"],
    requesterName: String(row.requester_name),
    requesterEmail: String(row.requester_email),
    assigneeEmail: row.assignee_email ? String(row.assignee_email) : null,
    siteName: row.site_name ? String(row.site_name) : null,
    siteId: row.site_id ? String(row.site_id) : null,
    assetTag: row.asset_tag ? String(row.asset_tag) : null,
    assetId: row.asset_id ? String(row.asset_id) : null,
    deviceId: row.device_id ? String(row.device_id) : null,
    deviceName: row.device_name ? String(row.device_name) : null,
    lockhavenAlertId: row.lockhaven_alert_id
      ? String(row.lockhaven_alert_id)
      : null,
    lockhavenSessionId: row.lockhaven_session_id
      ? String(row.lockhaven_session_id)
      : null,
    lockhavenAccessRequestId: row.lockhaven_access_request_id
      ? String(row.lockhaven_access_request_id)
      : null,
    recordingUrl: row.recording_url ? String(row.recording_url) : null,
    sessionReason: row.session_reason ? String(row.session_reason) : null,
    notes: String(row.notes ?? ""),
    timeSpentMinutes: Number(row.time_spent_minutes ?? 0),
    resolution: row.resolution ? String(row.resolution) : null,
    createdBySub: row.created_by_sub ? String(row.created_by_sub) : null,
    createdAt: new Date(String(row.created_at)),
    updatedAt: new Date(String(row.updated_at)),
    resolvedAt: row.resolved_at ? new Date(String(row.resolved_at)) : null,
  }
}

function mapNote(row: Record<string, unknown>): TicketNote {
  return {
    id: String(row.id),
    ticketId: String(row.ticket_id),
    authorEmail: String(row.author_email),
    authorName: String(row.author_name),
    body: String(row.body),
    minutes: Number(row.minutes ?? 0),
    createdAt: new Date(String(row.created_at)),
  }
}

function mapChange(row: Record<string, unknown>): ChangeRecord {
  return {
    id: String(row.id),
    number: Number(row.number),
    title: String(row.title),
    summary: String(row.summary ?? ""),
    status: row.status as ChangeRecord["status"],
    requestedByEmail: String(row.requested_by_email),
    requestedByName: String(row.requested_by_name),
    approvedByEmail: row.approved_by_email ? String(row.approved_by_email) : null,
    approvedAt: row.approved_at ? new Date(String(row.approved_at)) : null,
    lockhavenAccessRequestId: row.lockhaven_access_request_id
      ? String(row.lockhaven_access_request_id)
      : null,
    rollbackPlan: String(row.rollback_plan ?? ""),
    appliedAt: row.applied_at ? new Date(String(row.applied_at)) : null,
    createdAt: new Date(String(row.created_at)),
    updatedAt: new Date(String(row.updated_at)),
  }
}

function mapChangeEvent(row: Record<string, unknown>): ChangeEvent {
  return {
    id: String(row.id),
    changeId: String(row.change_id),
    actorEmail: String(row.actor_email),
    actorName: String(row.actor_name),
    action: String(row.action),
    detail: (row.detail as Record<string, unknown>) ?? {},
    createdAt: new Date(String(row.created_at)),
  }
}

export function createTicketStore(sql: Sql): TicketStore & {
  listTickets(filter: {
    status?: TicketStatus | "all"
    q?: string
  }): Promise<TicketRecord[]>
  listNotes(ticketId: string): Promise<TicketNote[]>
  ping(): Promise<boolean>
} {
  return {
    async ping() {
      const rows = await sql`select 1 as ok`
      return rows.length === 1
    },
    async findById(id) {
      const rows = await sql`select * from tickets where id = ${id} limit 1`
      return rows[0] ? mapTicket(rows[0] as Record<string, unknown>) : null
    },
    async findByAlertId(alertId) {
      const rows =
        await sql`select * from tickets where lockhaven_alert_id = ${alertId} limit 1`
      return rows[0] ? mapTicket(rows[0] as Record<string, unknown>) : null
    },
    async findByAccessRequestId(accessRequestId) {
      const rows =
        await sql`select * from tickets where lockhaven_access_request_id = ${accessRequestId} limit 1`
      return rows[0] ? mapTicket(rows[0] as Record<string, unknown>) : null
    },
    async findBySessionId(sessionId) {
      const rows =
        await sql`select * from tickets where lockhaven_session_id = ${sessionId} limit 1`
      return rows[0] ? mapTicket(rows[0] as Record<string, unknown>) : null
    },
    async create(input: NewTicket) {
      const rows = await sql`
        insert into tickets (
          title, severity, category, status, source,
          requester_name, requester_email, assignee_email,
          site_name, site_id, asset_tag, asset_id, device_id, device_name,
          lockhaven_alert_id, lockhaven_session_id, lockhaven_access_request_id,
          recording_url, session_reason, notes, time_spent_minutes, resolution,
          created_by_sub, resolved_at
        ) values (
          ${input.title}, ${input.severity}, ${input.category},
          ${input.status ?? "open"}, ${input.source},
          ${input.requesterName}, ${input.requesterEmail},
          ${input.assigneeEmail ?? null},
          ${input.siteName ?? null}, ${input.siteId ?? null},
          ${input.assetTag ?? null}, ${input.assetId ?? null},
          ${input.deviceId ?? null}, ${input.deviceName ?? null},
          ${input.lockhavenAlertId ?? null}, ${input.lockhavenSessionId ?? null},
          ${input.lockhavenAccessRequestId ?? null},
          ${input.recordingUrl ?? null}, ${input.sessionReason ?? null},
          ${input.notes ?? ""}, ${input.timeSpentMinutes ?? 0},
          ${input.resolution ?? null}, ${input.createdBySub ?? null},
          ${input.resolvedAt ?? null}
        )
        returning *
      `
      return mapTicket(rows[0] as Record<string, unknown>)
    },
    async update(id, patch: TicketPatch) {
      const rows = await sql`
        update tickets set
          title = coalesce(${patch.title ?? null}, title),
          severity = coalesce(${patch.severity ?? null}, severity),
          category = coalesce(${patch.category ?? null}, category),
          status = coalesce(${patch.status ?? null}, status),
          assignee_email = coalesce(${patch.assigneeEmail ?? null}, assignee_email),
          notes = coalesce(${patch.notes ?? null}, notes),
          time_spent_minutes = coalesce(${patch.timeSpentMinutes ?? null}, time_spent_minutes),
          resolution = case
            when ${patch.resolution === null} then null
            else coalesce(${patch.resolution ?? null}, resolution)
          end,
          resolved_at = case
            when ${patch.resolvedAt === null} then null
            else coalesce(${patch.resolvedAt ?? null}, resolved_at)
          end,
          updated_at = now()
        where id = ${id}
        returning *
      `
      if (!rows[0]) {
        throw new Error("ticket not found")
      }
      return mapTicket(rows[0] as Record<string, unknown>)
    },
    async addNote(ticketId, note: NewNote) {
      const minutes = note.minutes ?? 0
      const rows = await sql`
        insert into ticket_notes (ticket_id, author_email, author_name, body, minutes)
        values (${ticketId}, ${note.authorEmail}, ${note.authorName}, ${note.body}, ${minutes})
        returning *
      `
      if (minutes > 0) {
        await sql`
          update tickets
          set time_spent_minutes = time_spent_minutes + ${minutes},
              updated_at = now()
          where id = ${ticketId}
        `
      } else {
        await sql`update tickets set updated_at = now() where id = ${ticketId}`
      }
      return mapNote(rows[0] as Record<string, unknown>)
    },
    async listTickets(filter) {
      const status = filter.status && filter.status !== "all" ? filter.status : null
      const q = filter.q?.trim() ? `%${filter.q.trim()}%` : null
      const rows = await sql`
        select * from tickets
        where (${status}::text is null or status = ${status})
          and (
            ${q}::text is null
            or title ilike ${q}
            or requester_name ilike ${q}
            or asset_tag ilike ${q}
            or device_name ilike ${q}
            or site_name ilike ${q}
          )
        order by
          case severity
            when 'critical' then 0
            when 'high' then 1
            when 'medium' then 2
            else 3
          end,
          updated_at desc
        limit 200
      `
      return rows.map((row) => mapTicket(row as Record<string, unknown>))
    },
    async listNotes(ticketId) {
      const rows =
        await sql`select * from ticket_notes where ticket_id = ${ticketId} order by created_at asc`
      return rows.map((row) => mapNote(row as Record<string, unknown>))
    },
  }
}

export async function createChange(
  sql: Sql,
  input: {
    title: string
    summary: string
    rollbackPlan: string
    requestedByEmail: string
    requestedByName: string
    lockhavenAccessRequestId?: string | null
  }
) {
  const rows = await sql`
    insert into changes (
      title, summary, status, requested_by_email, requested_by_name,
      lockhaven_access_request_id, rollback_plan
    ) values (
      ${input.title}, ${input.summary}, 'draft',
      ${input.requestedByEmail}, ${input.requestedByName},
      ${input.lockhavenAccessRequestId ?? null}, ${input.rollbackPlan}
    )
    returning *
  `
  const change = mapChange(rows[0] as Record<string, unknown>)
  await sql`
    insert into change_events (change_id, actor_email, actor_name, action, detail)
    values (
      ${change.id}, ${input.requestedByEmail}, ${input.requestedByName},
      'created', ${sql.json({ status: "draft" })}
    )
  `
  return change
}

export async function getChange(sql: Sql, id: string) {
  const rows = await sql`select * from changes where id = ${id} limit 1`
  return rows[0] ? mapChange(rows[0] as Record<string, unknown>) : null
}

export async function listChanges(sql: Sql) {
  const rows = await sql`select * from changes order by updated_at desc limit 200`
  return rows.map((row) => mapChange(row as Record<string, unknown>))
}

export async function listChangeEvents(sql: Sql, changeId: string) {
  const rows =
    await sql`select * from change_events where change_id = ${changeId} order by created_at asc`
  return rows.map((row) => mapChangeEvent(row as Record<string, unknown>))
}

export async function saveChangeTransition(
  sql: Sql,
  input: {
    id: string
    status: ChangeStatus
    approvedByEmail: string | null
    approvedAt: Date | null
    appliedAt: Date | null
    actorEmail: string
    actorName: string
    action: string
    detail: Record<string, unknown>
  }
) {
  const rows = await sql`
    update changes set
      status = ${input.status},
      approved_by_email = coalesce(${input.approvedByEmail}, approved_by_email),
      approved_at = coalesce(${input.approvedAt}, approved_at),
      applied_at = coalesce(${input.appliedAt}, applied_at),
      updated_at = now()
    where id = ${input.id}
    returning *
  `
  await sql`
    insert into change_events (change_id, actor_email, actor_name, action, detail)
    values (
      ${input.id}, ${input.actorEmail}, ${input.actorName},
      ${input.action}, ${sql.json(JSON.parse(JSON.stringify(input.detail)))}
    )
  `
  return mapChange(rows[0] as Record<string, unknown>)
}

export async function recordIngest(
  sql: Sql,
  input: {
    source: string
    event: string
    ticketId: string | null
    payload: unknown
  }
) {
  await sql`
    insert into ingest_events (source, event, ticket_id, payload)
    values (
      ${input.source}, ${input.event}, ${input.ticketId},
      ${sql.json(JSON.parse(JSON.stringify(input.payload)))}
    )
  `
}
